name: 'Setup Build Environment'
description: 'Install system dependencies and Rust toolchain'
inputs:
  components:
    description: 'Rust components to install'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ cmake pkg-config libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libwayland-bin libxkbcommon-dev wayland-protocols libdecor-0-dev libegl1-mesa-dev libwayland-egl1-mesa
      shell: bash

    - name: Build and install GLFW 3.4
      run: |
        git clone --depth 1 --branch 3.4 https://github.com/glfw/glfw.git /tmp/glfw
        cd /tmp/glfw
        cmake -B build -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DGLFW_BUILD_WAYLAND=ON -DGLFW_BUILD_X11=ON
        cmake --build build
        sudo cmake --install build
        sudo ldconfig
      shell: bash

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: ${{ inputs.components }}
