//! The numeric key codes front ends expose (GLFW values, see
//! `processing_core::constants`) and their Bevy `KeyCode`s.

use bevy::input::keyboard::KeyCode;
use processing_core::constants as c;
use processing_core::error::{ProcessingError, Result};

macro_rules! key_table {
    ($($code:ident => $key:ident),* $(,)?) => {
        pub fn key_code_from_u32(code: u32) -> Result<KeyCode> {
            match code {
                $(c::$code => Ok(KeyCode::$key),)*
                _ => Err(ProcessingError::InvalidArgument(format!("unknown key code: {code}"))),
            }
        }

        pub fn key_code_to_u32(key: KeyCode) -> Option<u32> {
            match key {
                $(KeyCode::$key => Some(c::$code),)*
                _ => None,
            }
        }
    };
}

key_table! {
    KEY_A => KeyA,
    KEY_B => KeyB,
    KEY_C => KeyC,
    KEY_D => KeyD,
    KEY_E => KeyE,
    KEY_F => KeyF,
    KEY_G => KeyG,
    KEY_H => KeyH,
    KEY_I => KeyI,
    KEY_J => KeyJ,
    KEY_K => KeyK,
    KEY_L => KeyL,
    KEY_M => KeyM,
    KEY_N => KeyN,
    KEY_O => KeyO,
    KEY_P => KeyP,
    KEY_Q => KeyQ,
    KEY_R => KeyR,
    KEY_S => KeyS,
    KEY_T => KeyT,
    KEY_U => KeyU,
    KEY_V => KeyV,
    KEY_W => KeyW,
    KEY_X => KeyX,
    KEY_Y => KeyY,
    KEY_Z => KeyZ,
    KEY_0 => Digit0,
    KEY_1 => Digit1,
    KEY_2 => Digit2,
    KEY_3 => Digit3,
    KEY_4 => Digit4,
    KEY_5 => Digit5,
    KEY_6 => Digit6,
    KEY_7 => Digit7,
    KEY_8 => Digit8,
    KEY_9 => Digit9,
    SPACE => Space,
    QUOTE => Quote,
    COMMA => Comma,
    MINUS => Minus,
    PERIOD => Period,
    SLASH => Slash,
    SEMICOLON => Semicolon,
    EQUAL => Equal,
    BRACKET_LEFT => BracketLeft,
    BACKSLASH => Backslash,
    BRACKET_RIGHT => BracketRight,
    BACKQUOTE => Backquote,
    ESCAPE => Escape,
    ENTER => Enter,
    TAB => Tab,
    BACKSPACE => Backspace,
    INSERT => Insert,
    DELETE => Delete,
    RIGHT_ARROW => ArrowRight,
    LEFT_ARROW => ArrowLeft,
    DOWN => ArrowDown,
    UP => ArrowUp,
    PAGE_UP => PageUp,
    PAGE_DOWN => PageDown,
    HOME => Home,
    END => End,
    CAPS_LOCK => CapsLock,
    SCROLL_LOCK => ScrollLock,
    NUM_LOCK => NumLock,
    PRINT_SCREEN => PrintScreen,
    PAUSE => Pause,
    F1 => F1,
    F2 => F2,
    F3 => F3,
    F4 => F4,
    F5 => F5,
    F6 => F6,
    F7 => F7,
    F8 => F8,
    F9 => F9,
    F10 => F10,
    F11 => F11,
    F12 => F12,
    F13 => F13,
    F14 => F14,
    F15 => F15,
    F16 => F16,
    F17 => F17,
    F18 => F18,
    F19 => F19,
    F20 => F20,
    F21 => F21,
    F22 => F22,
    F23 => F23,
    F24 => F24,
    F25 => F25,
    NUMPAD_0 => Numpad0,
    NUMPAD_1 => Numpad1,
    NUMPAD_2 => Numpad2,
    NUMPAD_3 => Numpad3,
    NUMPAD_4 => Numpad4,
    NUMPAD_5 => Numpad5,
    NUMPAD_6 => Numpad6,
    NUMPAD_7 => Numpad7,
    NUMPAD_8 => Numpad8,
    NUMPAD_9 => Numpad9,
    NUMPAD_DECIMAL => NumpadDecimal,
    NUMPAD_DIVIDE => NumpadDivide,
    NUMPAD_MULTIPLY => NumpadMultiply,
    NUMPAD_SUBTRACT => NumpadSubtract,
    NUMPAD_ADD => NumpadAdd,
    NUMPAD_ENTER => NumpadEnter,
    NUMPAD_EQUAL => NumpadEqual,
    SHIFT => ShiftLeft,
    CONTROL => ControlLeft,
    ALT => AltLeft,
    SUPER => SuperLeft,
    SHIFT_RIGHT => ShiftRight,
    CONTROL_RIGHT => ControlRight,
    ALT_RIGHT => AltRight,
    SUPER_RIGHT => SuperRight,
    CONTEXT_MENU => ContextMenu,
}
