[package]
name = "processing_physics"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
avian3d = { path = "/Users/char/src/github.com/avianphysics/avian/crates/avian3d", default-features = false, features = [
  "3d",
  "parry-f32",
  "parallel",
  "collider-from-mesh",
] }
bevy = { workspace = true }
processing_core = { workspace = true }
processing_render = { workspace = true }
thiserror = "2"
