[package]
name = "processing_video"
version = "0.0.1"
edition = "2024"

[lints]
workspace = true

[dependencies]
bevy = { workspace = true }
nannou_video = { git = "https://github.com/nannou-org/nannou", branch = "bevy-refactor" }
processing_core = { workspace = true }
processing_render = { workspace = true }
thiserror = "2"
video-rs = "0.11"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-core-foundation = "0.3"
objc2-core-video = { version = "0.3", features = ["objc2-io-surface"] }
objc2-core-media = "0.3"
objc2-av-foundation = { version = "0.3", features = [
    "objc2-core-media",
    "objc2-core-video",
    "block2",
] }
objc2-io-surface = "0.3"
block2 = "0.6"

[dev-dependencies]
tempfile = "3"
